Selenium_HW
sergeyasheko/TAF pull request #1
Opened 2022-04-21 08:45 UTC by sergeyasheko

2022-04-25 11:56 UTC, wildpioneer requested changes

2022-04-25 11:56 UTC, wildpioneer commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(668,668);
Очень странная проверка

2022-04-25 11:56 UTC, wildpioneer commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(33,33);
Очень странная проверка

2022-04-25 11:56 UTC, wildpioneer commented on src/test/java/SmokeTestWithStar.java
> +    public void CalculatorForCalculatingLaminate() throws InterruptedException {
Не работает данный тест. Данные перед вводом значений не чистятся

2022-04-25 15:49 UTC, sergeyasheko commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(668,668);
Исправил

2022-04-25 15:49 UTC, sergeyasheko commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(33,33);
Исправил

2022-04-25 16:02 UTC, sergeyasheko commented on src/test/java/SmokeTestWithStar.java
> +    public void CalculatorForCalculatingLaminate() throws InterruptedException {
Исправил

2022-04-25 16:08 UTC, sergeyasheko commented on src/test/java/SmokeTestWithStar.java
> +    public void CalculatorForCalculatingLaminate() throws InterruptedException {
Исправил

2022-05-30 13:24 UTC, wildpioneer commented
Проверено

2022-05-30 13:24 UTC, closed without merging